import { jsonSchema as js, requestClaudeJson } from '@/lib/server/claude';
import { GUIDELINES_RULE, REFERENCE_FRAME_RULE, referenceSequences, shapeBrief, shapeRule, writtenByLine, type ReferenceFrame, type VideoWriter } from '@/lib/server/videoWriter';
import { videoAspectInfo } from '@/lib/videoModels';
import { productBrief, type ShopifyProductContext } from '@/lib/prompts/shopifyCreative';
import type { AdDesign } from '@/lib/server/referenceVideos';
import type { ReferenceImage } from '@/lib/server/referenceImages';
import type { ProviderUsage } from '@/lib/server/usage';
import { neutralise, resolveVideoStyle, type VideoStoryboard } from '@/lib/server/videoStoryboard';
import { isSpeakingStyle, type VideoStyle } from '@/lib/videoStyles';

/**
 * A Seedance 2.x product film built from reference images, written the way the Neeksha film
 * was: a look line, the product described exactly as its photos show it, one setting, timed
 * shots with one camera move each, sound in Seedance's own markup and a constraints line.
 * Claude Opus 5.5 writes the shot list as JSON after seeing the references and the reference
 * videos' sequences and frames; the prompt text itself is compiled here, so its structure
 * never drifts. Films cast Indian people, whom Seedance generates from the text (the images it
 * gets stay people-free: it refuses faces in them). Claude may ask for up to 2 people-free
 * scene images, which Gemini makes from the product photos and Seedance gets for those shots.
 */

export interface SeedanceFilm {
  hook: string;
  look: string;
  product: string;
  setting: string;
  /**
   * Who appears, generated by Seedance from the text (the images it gets stay people-free):
   * a cast of Indian people, one presenter who speaks to camera, only hands, or nobody.
   */
  people: 'none' | 'hands' | 'presenter' | 'cast';
  /** Who they are: age, look, clothing (Indian adults, never a real or famous person). */
  cast: string;
  /** "image" is the product reference a shot builds on (1-based, 0 for none). */
  shots: Array<{ t: string; framing: string; image: number; action: string; camera: string }>;
  music: string;
  sfx: string[];
  dialogue: string;
  avoid: string[];
  modelledOn?: string;
  /** Stills Claude asked for (shot is 1-based); Gemini makes them, then they join the references. */
  sceneImages?: Array<{ shot: number; prompt: string }>;
}

/** At most this many scene images per film. */
export const MAX_SCENE_IMAGES = 2;

type Json = Record<string, unknown>;

function clean(value: unknown, max: number): string {
  return typeof value === 'string' ? value.replace(/\s+/g, ' ').trim().slice(0, max) : '';
}

/** Long text cut at the last full sentence that fits, never mid-word. */
function sentences(value: unknown, max: number): string {
  const text = clean(value, 100_000);
  if (text.length <= max) return text;
  const cut = text.slice(0, max);
  const end = cut.lastIndexOf('. ');
  return end > max * 0.5 ? cut.slice(0, end + 1) : `${cut.slice(0, cut.lastIndexOf(' '))}…`;
}

function list(value: unknown, max: number, items: number): string[] {
  return Array.isArray(value) ? value.map((v) => clean(v, max)).filter(Boolean).slice(0, items) : [];
}

function shotCount(seconds: number): number {
  return seconds <= 8 ? 3 : seconds <= 15 ? 4 : 5;
}

/** Evenly timed shots when the writer's timing is missing. */
function evenTimes(count: number, seconds: number): string[] {
  const step = seconds / count;
  return Array.from({ length: count }, (_, i) => `${Math.round(i * step)}-${Math.round((i + 1) * step)}s`);
}

/**
 * How each style is filmed. Every film casts Indian people (Seedance generates them from the
 * text) except intimate wear, which video models refuse to show on a person.
 */
function styleDirection(style: string, garment: boolean, sensitive: boolean): string {
  if (sensitive) {
    return 'A premium product film: the product is the only subject, no person at any point. Motion comes from slow camera moves, light travelling across it and at most a soft breeze on light fabric.';
  }
  const wears = 'wears exactly the garment in the reference images (same colours, weave, border and pattern)';
  switch (style) {
    case 'ugc':
      return garment
        ? `A real customer's phone video: ONE Indian woman or man (describe them in "cast") ${wears}, films themselves at home on a phone propped at eye level, talks to the camera like a friend and shows the garment off with small, slow movements. Natural daylight.`
        : 'A real customer\'s phone video: ONE Indian adult (describe them in "cast") films themselves at home at arm\'s length, talks to the camera like a friend and shows the product up close. Handheld, natural daylight.';
    case 'talking_head':
      return garment
        ? `A talking-head ad: ONE Indian presenter (describe them in "cast") ${wears} and speaks straight into the lens in a clean real setting. Steady camera, framed from the waist up or wider.`
        : 'A talking-head ad: ONE Indian presenter (describe them in "cast") speaks straight into the lens in a clean real setting, the product clearly visible in their hands or beside them. Steady camera.';
    case 'demo':
      return garment
        ? `A styling demo: an Indian model (describe them in "cast") ${wears} and shows it: smoothing the pallu, adjusting the drape, a slow half turn, face visible. Slow, graceful movements so the pattern stays readable; include one close-up of the fabric.`
        : 'A hands-on demo: an Indian adult (describe them in "cast") uses the product in a clear chain of actions that makes its benefit visible: their hands up close, and their face in at least one shot reacting to the result.';
    default:
      return garment
        ? `A premium fashion film: an Indian model (describe them in "cast") ${wears}, face visible, in a real Indian setting. Slow, graceful movement (a turn, a few steps, the pallu settling) so the drape, border and pattern stay readable; include at least one close-up of the fabric. Nobody talks to the camera.`
        : 'A premium lifestyle film: one or two Indian adults (describe them in "cast") use or enjoy the product in a real Indian setting, faces visible, nobody talking to the camera. Include at least one hero close-up of the product, and end on a calm hero shot.';
  }
}

function fallbackFilm(context: ShopifyProductContext | undefined, seconds: number): SeedanceFilm {
  const times = evenTimes(4, seconds);
  const name = context?.title || 'the product';
  return {
    hook: 'A slow, luminous reveal of the product',
    look: 'luxury product film. Photoreal, cinematic 35mm look, soft natural daylight, shallow depth of field, rich but true colours, fine film grain',
    product: `${name}, exactly as the reference images show it`,
    setting: 'a calm, softly lit studio corner with warm neutral walls and a sunlit floor; daylight from a tall window on the left',
    people: 'none',
    cast: '',
    shots: [
      { t: times[0], framing: 'Extreme close-up', image: 1, action: 'A warm glint of sunlight sweeps slowly across the product’s finest detail', camera: 'Slow lateral slide' },
      { t: times[1], framing: 'Close-up', image: 1, action: 'The light moves across its surface, revealing texture and colour', camera: 'Slow downward tracking shot' },
      { t: times[2], framing: 'Medium shot', image: 1, action: 'The whole product comes into view, standing still in the light', camera: 'Slow push-in' },
      { t: times[3], framing: 'Wide shot', image: 1, action: 'The product rests in the sunlit setting, perfectly still. Hold on this final frame', camera: 'Slow pull-back' },
    ],
    music: 'a slow, elegant instrumental melody, calm and premium',
    sfx: ['soft room ambience'],
    dialogue: '',
    avoid: [],
  };
}

const FILM_SCHEMA = js.obj({
  hook: js.str,
  look: js.str,
  product: js.str,
  setting: js.str,
  people: js.oneOf(['none', 'hands', 'presenter', 'cast']),
  cast: js.str,
  shots: js.list(js.obj({ t: js.str, framing: js.str, image: js.int, action: js.str, camera: js.str })),
  music: js.str,
  sfx: js.strList,
  dialogue: js.str,
  avoid: js.strList,
  modelledOn: js.int,
  sceneImages: js.list(js.obj({ shot: js.int, prompt: js.str })),
});

const FILM_SYSTEM = 'You are the creative director and director of photography of a top Indian D2C video studio. You write product video ads for ByteDance Seedance 2.5 as a structured shot list; Visicraft turns it into the exact prompt Seedance receives and shows it to the brand for approval before anything renders. You model the structure, pacing and camera language of the reference videos the brand chose (their timed beats were watched in full by Gemini), but never copy their brand, product, people, wording or claims.';

/**
 * Claude Opus 5.5 writes the shot list after looking at the product's reference images and
 * the reference videos' timed sequences and frames. A template film is used, and said so, if
 * Claude fails.
 */
export async function writeSeedanceFilm(options: {
  context?: ShopifyProductContext;
  identityManifest?: string;
  userDirection?: string;
  adPatterns?: string;
  referenceDesigns?: AdDesign[];
  durationSeconds: number;
  /** The video's shape (9:16 unless picked otherwise). */
  aspectRatio?: string;
  style?: VideoStyle;
  productKind?: 'packaged' | 'apparel' | 'object';
  productSpec?: string;
  never?: string[];
  sensitive?: boolean;
  /** The project's guidelines (Markdown), when the video is made in a project. */
  guidelines?: string;
  /** The reference shows the product on a display mannequin (the store photo's model replaced). */
  onMannequin?: boolean;
  /** The product references, in the order they are sent (Image 1..N). */
  references: ReferenceImage[];
  /** Frames of the reference videos, for Claude only (never sent to Seedance). */
  referenceFrames?: ReferenceFrame[];
  /** Claude may ask for scene images (Gemini makes them for Seedance). */
  allowSceneImages?: boolean;
}): Promise<{ film: SeedanceFilm; style: Exclude<VideoStyle, 'any'>; usage?: ProviderUsage; writer: VideoWriter }> {
  const seconds = options.durationSeconds;
  const garment = options.productKind === 'apparel';
  const style = resolveVideoStyle(options.style, options.referenceDesigns, options.sensitive);
  const sensitive = Boolean(options.sensitive);
  const speaking = isSpeakingStyle(style) && !sensitive;
  const count = shotCount(seconds);
  const maxWords = Math.max(10, Math.round(seconds * 2.2));
  const designs = (options.referenceDesigns ?? []).filter((d) => d.sequence?.length).slice(0, 3);
  const references = options.references.slice(0, 6);
  const referenceFrames = (options.referenceFrames ?? []).slice(0, 8);
  const guidelines = options.guidelines?.trim();

  const shape = shapeRule(options.aspectRatio);
  const prompt = `Write a ${seconds}-second ${shapeBrief(options.aspectRatio)} for this product, to be generated by ByteDance Seedance 2.5 from the product's reference images above (reference-to-video: it builds every shot from these images and your words, there is no first frame). Goal: the most realistic, premium, scroll-stopping clip possible, with the product exactly as in its photos.

${styleDirection(style, garment, Boolean(options.sensitive))}${shape ? `\n${shape}` : ''}${options.onMannequin ? '\nThe reference image shows the product on a faceless ivory display mannequin (it replaced the model in the store photo). Keep the product on that mannequin in every shot: the mannequin stays perfectly still and is never removed, and no person appears.' : ''}${options.sensitive ? '\nWording (strict): never use words such as lingerie, underwear, sexy, sensual, seductive, intimate, bedroom, boudoir, body or skin; call the product "the set" or "the garment".' : ''}

${productBrief(options.context)}
Product identity notes: ${clean(options.identityManifest, 1200) || 'n/a'}
${options.productSpec ? `Exact product spec (name these details precisely in "product"):\n${options.productSpec.slice(0, 2500)}\n` : ''}${options.never?.length ? `Never show: ${options.never.join('; ')}\n` : ''}${options.userDirection ? `Client direction: ${clean(options.userDirection, 1500)}\n` : ''}${guidelines ? `${GUIDELINES_RULE}\n` : ''}${options.adPatterns ? `\nWHAT THE REFERENCE VIDEOS DO:\n${clean(options.adPatterns, 2000)}\n` : ''}${designs.length ? `\nTHE REFERENCE VIDEOS THE BRAND CHOSE, WATCHED IN FULL BY GEMINI. Turn the sequence of #1 into our shot list: keep its timing, shot sizes, camera moves and the order of its beats (hook, reveal, proof, call to action), with our product and our setting${designs.length > 1 ? '; use the others for extra ideas' : ''}:\n${referenceSequences(designs)}\n` : '\nNo reference videos were given for this one; write the strongest film for the product and style.\n'}
Reference images (attached above, in this order; these are what Seedance receives):
${references.map((r, i) => `Image ${i + 1}: ${r.label}`).join('\n')}
${referenceFrames.length ? `\n${REFERENCE_FRAME_RULE}\n` : ''}
How to write it (Seedance's own prompt rules):
- "product": exactly what the reference images show, in at most 90 words: colours, materials, finish, shape, patterns, and any printed text or logo word for word as it appears. Never invent details, text or features.
- "shots": exactly ${count} shots whose "t" values cover 0-${seconds}s end to end, written like "0-3s". Each has a framing (extreme close-up, close-up, medium or wide${guidelines ? '; written the way the guidelines teach when they do, e.g. with the lens and exactly what must stay visible, as one sentence without full stops, at most 150 characters' : ''}), the reference image it builds on ("image", 1-${references.length}), a concrete physical action with its speed and size (e.g. "a warm glint of sunlight sweeps slowly across the zari border", "the pallu lifts a few centimetres and settles"), and exactly ONE camera movement (slow push-in, slow lateral slide, slow downward tracking shot, slow orbit, slow pull-back or fixed camera${guidelines ? ', or the camera language the guidelines teach, in one sentence' : ''}). Prefer slow, gentle, continuous motion; no fast or large movements.
- Shot 1 must stop the scroll within 1.5 seconds (a macro glint, a reveal, a satisfying motion). The last shot is a calm hero shot of the whole product, held still.
- "setting": ONE location suited to the product and its price tier (Indian where it fits), with its light direction and quality. All shots happen there.
- "look": one line of image quality and style, e.g. "luxury product film. Photoreal, cinematic 35mm look, soft natural daylight, shallow depth of field, rich but true colours, fine film grain"${guidelines ? ' (name no lens here when the shots name their own)' : ''}.
- Sound: "music" (an original, simple instrumental bed: instruments, tempo, mood; never name or imitate a song, artist, film score or famous tune, since Seedance stops videos whose music sounds like an existing song) and 1-3 "sfx" (quiet, specific sounds).${speaking ? ` "dialogue": ONE spoken line in natural Indian English, at most ${maxWords} words, its first words are the hook, one concrete benefit, no prices or competitor names.` : ' "dialogue" is "" (no voice).'}
- "people": ${sensitive ? '"none".' : `${speaking ? '"presenter"' : '"cast"'}. Use "none" only if the client direction asks for a product-only film, "hands" only if it asks for hands only.`}
- "cast": ${sensitive ? '"".' : 'who appears, in at most 45 words: 1-2 Indian adults with age range, look, skin tone, hair and clothing that suit the brand, the product and its price tier (for a garment, they wear the product itself). Real-looking everyday people, never a real or famous person. Faces stay the same in every shot.'}
- "avoid": 4-8 specific wrong versions to keep out (e.g. "extra products", "the logo misspelled", "the car turned blue").${sensitive ? '' : ' Never list people, faces or voices.'}
- "hook": one sentence for the brand describing the idea. "modelledOn": the number of the reference video you modelled, or 0.
- "sceneImages": ${options.allowSceneImages ? `ask for a still image ONLY when a shot needs a picture the reference images cannot give (the product placed in its setting for the opening scene, the product in use somewhere, an angle no photo shows); otherwise []. At most ${MAX_SCENE_IMAGES}. Visicraft has Gemini make each one from the product photos, with the product kept exact, and gives it to Seedance as an extra reference image for that shot. Each item: "shot" (the 1-based shot number) and "prompt" (40-80 words describing the still photo: setting, light, framing and where the product sits; no people, faces or hands, since Seedance adds the cast in that shot from your words; no text other than the product's own).` : 'always [] (not available for this video).'}`;

  try {
    const { json: parsed, usage } = await requestClaudeJson<Json>({
      system: FILM_SYSTEM,
      context: guidelines ? [`PROJECT GUIDELINES (Markdown):\n\n${guidelines.slice(0, 50_000)}`] : [],
      images: [
        ...references.map((r, i) => ({ label: `Image ${i + 1} (${r.label || 'product'}):`, url: r.url })),
        ...referenceFrames.map((frame) => ({ label: `${frame.label} (FOR YOU ONLY, not sent to Seedance):`, url: frame.url })),
      ],
      prompt,
      schema: FILM_SCHEMA,
      timeoutMs: 150_000,
    });
    const times = evenTimes(count, seconds);
    const shots = (Array.isArray(parsed.shots) ? parsed.shots : [])
      .map((shotValue, i) => {
        const shot = (shotValue && typeof shotValue === 'object' ? shotValue : {}) as Json;
        const image = Number(shot.image);
        return {
          t: /^\d+(\.\d+)?-\d+(\.\d+)?s$/.test(clean(shot.t, 12)) ? clean(shot.t, 12) : times[i] ?? `${seconds}s`,
          framing: clean(shot.framing, 150) || 'Close-up',
          image: Number.isInteger(image) && image >= 1 && image <= references.length ? image : 0,
          action: clean(shot.action, 320),
          camera: clean(shot.camera, 120) || 'Slow push-in',
        };
      })
      .filter((shot) => shot.action)
      .slice(0, count + 1);
    if (shots.length < 2 || !clean(parsed.product, 10)) throw new Error('The film plan was incomplete');
    // Intimate wear is never shown on a person; otherwise the writer casts (or the client asked otherwise).
    const people: SeedanceFilm['people'] = sensitive
      ? 'none'
      : parsed.people === 'presenter' && speaking
        ? 'presenter'
        : parsed.people === 'hands' || parsed.people === 'none'
          ? parsed.people
          : 'cast';
    const modelled = Number(parsed.modelledOn) > 0 ? designs[Math.max(0, Number(parsed.modelledOn) - 1)] : undefined;
    return {
      film: {
        hook: clean(parsed.hook, 200),
        look: clean(parsed.look, 260) || fallbackFilm(options.context, seconds).look,
        product: sentences(parsed.product, 1100),
        setting: clean(parsed.setting, 400),
        people,
        cast: people === 'presenter' || people === 'cast' ? clean(parsed.cast, 320) : '',
        shots,
        music: clean(parsed.music, 200),
        sfx: list(parsed.sfx, 80, 3),
        dialogue: people === 'presenter' ? clean(parsed.dialogue, 240).replace(/^["“{]|["”}]$/g, '') : '',
        avoid: list(parsed.avoid, 80, 8),
        modelledOn: modelled?.pageName,
        sceneImages: options.allowSceneImages
          ? (Array.isArray(parsed.sceneImages) ? parsed.sceneImages : [])
              .map((item) => {
                const request = (item && typeof item === 'object' ? item : {}) as Json;
                const shot = Number(request.shot);
                return { shot, prompt: clean(request.prompt, 600) };
              })
              .filter((request) => Number.isInteger(request.shot) && request.shot >= 1 && request.shot <= shots.length && request.prompt)
              // One image per shot: a second request for the same shot would never be used.
              .filter((request, index, all) => all.findIndex((other) => other.shot === request.shot) === index)
              .slice(0, MAX_SCENE_IMAGES)
          : [],
      },
      style,
      usage,
      writer: { writtenBy: writtenByLine(designs, modelled?.pageName) },
    };
  } catch (error) {
    const reason = error instanceof Error ? error.message : 'Claude failed';
    console.warn('Seedance film writing (Claude) failed, using the template film:', reason);
    return {
      film: fallbackFilm(options.context, seconds),
      style,
      writer: { writtenBy: 'A basic template', fallbackReason: `The prompt couldn't be written (${reason}), so this is a basic template. Edit it, or cancel and try again.` },
    };
  }
}

/**
 * The exact prompt Seedance receives. `opening` puts a person-free hero frame first (Image 1,
 * the scene the film opens on) and shifts the product references to Image 2 onwards. Image
 * numbers appear only as "(Image k)" and "Opening scene: Image 1." so the review screen can
 * drop a reference and renumber the rest.
 */
/** Sentence case at the joins of the compiled prompt. */
const upperFirst = (text: string) => text.charAt(0).toUpperCase() + text.slice(1);
/** The style line reads on from "10-second vertical" (or horizontal, square…); acronyms (UGC, 4K) are left alone. */
const lowerLook = (text: string) => (/^[A-Z][a-z]/.test(text) ? text.charAt(0).toLowerCase() + text.slice(1) : text);
/** A leading article after a colon ("…: a sheer saree"); names and brands keep their capitals. */
const lowerArticle = (text: string) => text.replace(/^(A|An|The)\b/, (word) => word.toLowerCase());
const trimEnd = (text: string) => text.replace(/[.\s]+$/, '');

export function compileSeedanceFilm(film: SeedanceFilm, options: {
  durationSeconds: number;
  /** The video's shape, named on the first line (9:16 unless picked otherwise). */
  aspectRatio?: string;
  opening: boolean;
  family: '2.0' | '2.5';
  audio: boolean;
  /** The references show the product on a display mannequin, which must stay in the film. */
  mannequin?: boolean;
  /** Intimate wear and similar: words that trip the video model's filter are replaced. */
  sensitive?: boolean;
}): string {
  const offset = options.opening ? 1 : 0;
  const cast = trimEnd(film.cast || 'an Indian adult');
  const peopleLine = film.people === 'none'
    ? options.mannequin
      ? 'The product is the only subject, displayed on a faceless ivory display mannequin that never moves: no people, no faces, no hands.'
      : 'The product is the only subject: no people, no hands, no mannequin.'
    : film.people === 'hands'
      ? "Only an adult's hands appear, never a face."
      : film.people === 'presenter'
        ? `One presenter speaks to the camera: ${lowerArticle(cast)}. Their face looks natural and real and stays the same in every shot.`
        : `Cast: ${lowerArticle(cast)}. Faces look natural and real and stay the same in every shot.`;
  const shots = film.shots.map((shot, i) => {
    const ref = shot.image > 0 ? ` (Image ${shot.image + offset})` : '';
    const action = shot.action.replace(/[.\s]+$/, '');
    // One sentence each for framing and camera, so the shot reads back as framing, action, camera.
    const framing = trimEnd(shot.framing).replace(/\.\s+/g, ', ');
    const camera = trimEnd(shot.camera).replace(/\.\s+/g, '; ');
    return `Shot ${i + 1} (${shot.t}): ${upperFirst(framing)}. ${upperFirst(action)}${ref}. ${upperFirst(camera)}.`;
  });
  const sound = !options.audio
    ? ''
    : options.family === '2.5'
      ? `Sound: ${film.music ? `(original music, not based on any existing song: ${film.music})` : ''}${film.sfx.map((s) => ` <${s}>`).join('')}. ${film.dialogue ? `The presenter says, in English: {${film.dialogue}}` : 'No voice, no dialogue, no singing.'}`
      : `Sound: ${[film.music && `original music, not based on any existing song: ${film.music}`, film.sfx.length && `effects: ${film.sfx.join(', ')}`].filter(Boolean).join('; ')}. ${film.dialogue ? `The presenter says: "${film.dialogue}"` : 'No voice, no dialogue, no singing.'}`;
  const who = film.people === 'none'
    ? (options.mannequin ? 'No people, faces or hands; the mannequin stays still. ' : 'No people, faces or hands. ')
    : film.people === 'hands'
      ? 'No faces. '
      : film.people === 'presenter'
        ? 'Only the one presenter appears, never a famous person. '
        : 'Only the cast appears, never a famous person. ';
  const avoid = film.avoid.length ? ` Avoid: ${film.avoid.join(', ')}.` : '';
  const text = [
    `${options.durationSeconds}-second ${videoAspectInfo(options.aspectRatio).orientation} ${lowerLook(trimEnd(film.look))}. ${peopleLine}`,
    '',
    `The product is exactly the one in the reference images: ${lowerArticle(trimEnd(film.product))}. Keep its colours, materials, shape, pattern and any printed text exactly as in the reference images in every shot${film.people === 'presenter' || film.people === 'cast' ? ', also when it is worn or held' : ''}.`,
    '',
    ...(options.opening ? ['Opening scene: Image 1.', ''] : []),
    `Setting: ${lowerArticle(trimEnd(film.setting))}.`,
    '',
    ...shots,
    '',
    ...(sound ? [sound, ''] : []),
    `Constraints: keep it subtitle-free and avoid generating any text or subtitles; do not add any logo or watermark that is not on the product itself. ${who}Do not change the product's colours, shape, pattern or printed text; no morphing, warping or melting; no flicker; one location only.${avoid}`,
  ].join('\n').replace(/\n{3,}/g, '\n\n');
  return (options.sensitive ? neutralise(text) : text).slice(0, 6000);
}

/** The film as a storyboard for the pipeline view (hook, beats, the JSON behind the prompt). */
export function filmStoryboard(film: SeedanceFilm, prompt: string, style: Exclude<VideoStyle, 'any'>): VideoStoryboard {
  return {
    hook: film.hook || film.shots[0]?.action || 'Product film',
    shots: film.shots.map((s) => ({ t: s.t, action: s.action, camera: s.camera, purpose: s.framing })),
    mood: film.look,
    modelledOn: film.modelledOn,
    style,
    script: film.dialogue || undefined,
    promptJson: film as unknown as Record<string, unknown>,
    prompt,
    negativePrompt: '',
  };
}
