import axios from 'axios';

interface GeminiPart {
  text?: string;
  inlineData?: {
    mimeType: string;
    data: string;
  };
}

interface GeminiRequest {
  contents: Array<{
    parts: GeminiPart[];
  }>;
  generationConfig?: {
    responseModalities?: string[];
    imageConfig?: {
      aspectRatio?: string;
      imageSize?: string;
    };
  };
}

interface GeminiResponse {
  candidates: Array<{
    content: {
      parts: Array<{
        text?: string;
        inlineData?: {
          mimeType: string;
          data: string;
        };
      }>;
    };
  }>;
}

export async function generateThumbnail(
  referenceImage: string,
  sourceImages: string[],
  prompt?: string
): Promise<string[]> {
  const apiKey = process.env.GEMINI_API_KEY!;

  if (!apiKey) {
    throw new Error('GEMINI_API_KEY is not configured. Please add it to your .env.local file.');
  }

  try {
    console.log('🎨 Generating thumbnail with Gemini API...');
    console.log('Reference image:', referenceImage.substring(0, 50) + '...');
    console.log('Source images:', sourceImages.length);
    
    // Download and convert images to base64
    const referenceBase64 = await urlToBase64(referenceImage);
    const sourceBase64Array = await Promise.all(
      sourceImages.map(url => urlToBase64(url))
    );

    // Build the prompt
    const fullPrompt = prompt || 
      'Create a professional, eye-catching YouTube thumbnail by combining these images. ' +
      'Use the reference image as style inspiration and incorporate the source images creatively. ' +
      'Make it vibrant, engaging, and optimized for YouTube with bold text placement areas.';

    // Build request parts: prompt + all images
    const parts: GeminiPart[] = [
      { text: fullPrompt },
      { inlineData: { mimeType: 'image/jpeg', data: referenceBase64 } },
      ...sourceBase64Array.map(data => ({
        inlineData: { mimeType: 'image/jpeg', data }
      }))
    ];

    const requestData: GeminiRequest = {
      contents: [{
        parts
      }],
      generationConfig: {
        responseModalities: ['IMAGE'],
        imageConfig: {
          aspectRatio: '16:9',
          imageSize: '2K'
        }
      }
    };

    console.log('📤 Sending request to Gemini API...');
    
    const response = await axios.post<GeminiResponse>(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-3-pro-image-preview:generateContent`,
      requestData,
      {
        headers: {
          'Content-Type': 'application/json',
          'x-goog-api-key': apiKey,
        },
        timeout: 120000, // 2 minutes timeout
      }
    );

    console.log('✅ Received response from Gemini');

    // Extract generated image from response
    const candidate = response.data.candidates?.[0];
    if (!candidate) {
      throw new Error('No response from Gemini API');
    }

    const imageParts = candidate.content.parts.filter(part => part.inlineData);
    if (imageParts.length === 0) {
      throw new Error('No image generated by Gemini API');
    }

    // Convert base64 images to data URLs
    const generatedImages = imageParts.map(part => {
      const base64Data = part.inlineData!.data;
      const mimeType = part.inlineData!.mimeType;
      return `data:${mimeType};base64,${base64Data}`;
    });

    console.log(`🎉 Generated ${generatedImages.length} image(s)`);
    
    return generatedImages;
  } catch (error) {
    if (axios.isAxiosError(error)) {
      const errorMessage = error.response?.data?.error?.message || 
                          error.response?.data?.message || 
                          error.message;
      const statusCode = error.response?.status;
      
      console.error('❌ Gemini API Error:', {
        status: statusCode,
        message: errorMessage,
        data: error.response?.data
      });
      
      if (statusCode === 401 || statusCode === 403) {
        throw new Error('Invalid Gemini API key. Please check your GEMINI_API_KEY in .env.local');
      }
      
      if (statusCode === 429) {
        throw new Error('Rate limit exceeded. Please try again in a moment.');
      }
      
      throw new Error(`Gemini API error: ${errorMessage}`);
    }
    console.error('❌ Unexpected error:', error);
    throw error;
  }
}

async function urlToBase64(imageUrl: string): Promise<string> {
  try {
    const response = await axios.get(imageUrl, { 
      responseType: 'arraybuffer',
      timeout: 30000
    });
    const base64 = Buffer.from(response.data, 'binary').toString('base64');
    return base64;
  } catch (error) {
    console.error('Failed to download image:', imageUrl);
    throw new Error(`Failed to download image: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}

export async function imageToBase64(imageUrl: string): Promise<string> {
  const base64 = await urlToBase64(imageUrl);
  return `data:image/jpeg;base64,${base64}`;
}
